/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 08 19:50:50 GMT 2018
 */
package DeTest;

import De.Face;
import De.Ressource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Face_ESTest extends Face_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face((Integer) null, ressource0);
      Integer integer0 = face0.getValeur();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face(integer0, ressource0);
      Integer integer1 = face0.getValeur();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face(integer0, ressource0);
      Integer integer1 = face0.getValeur();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(2171);
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face(integer0, ressource0);
      face0.setValeur(integer0);
      assertEquals(2171, (int)face0.getValeur());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face(integer0, ressource0);
      Ressource ressource1 = face0.getRes();
      assertSame(ressource0, ressource1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face(integer0, ressource0);
      Integer integer1 = face0.getValeur();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Ressource ressource0 = Ressource.OR;
      Face face0 = new Face((Integer) null, ressource0);
      face0.setRes(ressource0);
      assertNull(face0.getValeur());
  }
}
