/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 08 19:51:33 GMT 2018
 */

package DeTest;

import De.Ressource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ressource_ESTest extends Ressource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ressource[] ressourceArray0 = Ressource.values();
      assertEquals(1, ressourceArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Ressource ressource0 = Ressource.valueOf("OR");
      assertEquals(Ressource.OR, ressource0);
  }
}
