/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 08 19:51:46 GMT 2018
 */

package GameTest;

import Game.Inventaire;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Inventaire_ESTest extends Inventaire_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Inventaire inventaire0 = new Inventaire();
      inventaire0.setInventaire(803);
      int int0 = inventaire0.getInventaire();
      assertEquals(803, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Inventaire inventaire0 = new Inventaire();
      int int0 = inventaire0.getInventaire();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Inventaire inventaire0 = new Inventaire();
      inventaire0.setInventaire((-4094));
      int int0 = inventaire0.getInventaire();
      assertEquals((-4094), int0);
  }
}
