/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 08 19:50:07 GMT 2018
 */

package GameTest;

import Game.Partie;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Partie_ESTest extends Partie_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Partie.main((String[]) null);
      Partie.main((String[]) null);
      Partie.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Partie partie0 = new Partie();
  }
}
